In [1]:
import torch

In [4]:
x = torch.arange(4.0)

In [5]:
x

tensor([0., 1., 2., 3.])

In [7]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [9]:
y = 2 * torch.dot(x, x)

In [10]:
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.grad_fn.register_hook

<function MulBackward0.register_hook>

In [16]:
x.grad

In [17]:
y.backward()

In [18]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [19]:
x.grad == 4*x

tensor([True, True, True, True])

In [20]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [21]:
y = x.sum()

In [22]:
y.backward()

In [23]:
x.grad

tensor([1., 1., 1., 1.])

In [24]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [25]:
y = x*x

In [26]:
y.sum().backward()

In [27]:
x.grad

tensor([0., 2., 4., 6.])

In [28]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [29]:
y = x* x

In [30]:
u = y.detach()

In [31]:
z= u*x

In [32]:
z.sum().backward()

In [33]:
x.grad == u

tensor([True, True, True, True])

In [34]:
u

tensor([0., 1., 4., 9.])

In [35]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [36]:
y.sum().backward()

In [37]:
x.grad == 2*x

tensor([True, True, True, True])

In [44]:
a = torch.randn(size=(),requires_grad=True)

In [48]:
print(a)
a.norm(),a.sum()

tensor(-0.5552, requires_grad=True)


(tensor(0.5552, grad_fn=<LinalgVectorNormBackward0>),
 tensor(-0.5552, grad_fn=<SumBackward0>))

In [40]:
def f(a):
    b = a*2
    while b.norm() <1000:
        b = b*2
    if b.sum() >0:
        c = b
    else:
        c= 100*b
    return c    

In [41]:
d = f(a)

In [42]:
d.backward()

In [43]:
a.grad

tensor(204800.)